package datas

import (
	"gofiber/app/models/model/adminsModel"
	"gofiber/app/models/model/systemsModel"
)

// InitCountry 初始化国家
func InitCountry() []*systemsModel.Country {
	return []*systemsModel.Country{
		{AdminId: adminsModel.SuperAdminId, Name: "中国", Alias: "China", Code: "86", Icon: "/assets/country/china.png", Iso1: "CN", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "台湾", Alias: "Taiwan", Code: "886", Icon: "/assets/country/taiwan.png", Iso1: "TW", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "香港", Alias: "Hong kong", Code: "852", Icon: "/assets/country/hongkong.png", Iso1: "HK", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "澳门", Alias: "Macao", Code: "853", Icon: "/assets/country/macao.png", Iso1: "MO", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "蒙古", Alias: "Mongolia", Code: "976", Icon: "/assets/country/mongolia.png", Iso1: "MN", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "朝鲜", Alias: "North Korea", Code: "850", Icon: "/assets/country/north_korea.png", Iso1: "KP", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "韩国", Alias: "South Korea", Code: "82", Icon: "/assets/country/south_korea.png", Iso1: "KR", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "日本", Alias: "Japan", Code: "81", Icon: "/assets/country/japan.png", Iso1: "JP", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "菲律宾", Alias: "Philippines", Code: "63", Icon: "/assets/country/philippines.png", Iso1: "PH", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "越南", Alias: "Vietnam", Code: "84", Icon: "/assets/country/vietnam.png", Iso1: "VN", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "老挝", Alias: "Laos", Code: "856", Icon: "/assets/country/laos.png", Iso1: "LA", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "柬埔寨", Alias: "Cambodia", Code: "855", Icon: "/assets/country/cambodia.png", Iso1: "kH", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "缅甸", Alias: "Myanmar", Code: "95", Icon: "/assets/country/myanmar.png", Iso1: "MM", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "泰国", Alias: "Thailand", Code: "66", Icon: "/assets/country/thailand.png", Iso1: "TH", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "马来西亚", Alias: "Malaysia", Code: "60", Icon: "/assets/country/malaysia.png", Iso1: "MY", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "文莱", Alias: "Brunei", Code: "673", Icon: "/assets/country/brunei.png", Iso1: "BN", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "新加坡", Alias: "Singapore", Code: "65", Icon: "/assets/country/singapore.png", Iso1: "SG", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "印度尼西亚", Alias: "Indonesia", Code: "62", Icon: "/assets/country/indonesia.png", Iso1: "ID", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "东帝汶", Alias: "Timor-Leste", Code: "670", Icon: "/assets/country/east_timor.png", Iso1: "TL", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "尼泊尔", Alias: "Nepal", Code: "977", Icon: "/assets/country/nepal.png", Iso1: "NP", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "不丹", Alias: "Bhutan", Code: "975", Icon: "/assets/country/bhutan.png", Iso1: "BT", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "孟加拉国", Alias: "Bangladesh", Code: "880", Icon: "/assets/country/bangladesh.png", Iso1: "BD", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "印度", Alias: "India", Code: "91", Icon: "/assets/country/india.png", Iso1: "IN", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "巴基斯坦", Alias: "Pakistan", Code: "92", Icon: "/assets/country/pakistan.png", Iso1: "PK", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "斯里兰卡", Alias: "SriLanka", Code: "94", Icon: "/assets/country/sri_lanka.png", Iso1: "LK", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "马尔代夫", Alias: "Maldives", Code: "960", Icon: "/assets/country/maldives.png", Iso1: "MV", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "哈萨克斯坦", Alias: "Kazakhstan", Code: "7", Icon: "/assets/country/kazakhstan.png", Iso1: "KZ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "吉尔吉斯斯坦", Alias: "Kyrgyzstan", Code: "996", Icon: "/assets/country/kyrgyzstan.png", Iso1: "KG", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "塔吉克斯坦", Alias: "Tajikistan", Code: "992", Icon: "/assets/country/tajikistan.png", Iso1: "TJ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "乌兹别克斯坦", Alias: "Uzbekistan", Code: "998", Icon: "/assets/country/uzbekistan.png", Iso1: "UZ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "土库曼斯坦", Alias: "Turkmenistan", Code: "993", Icon: "/assets/country/turkmenistan.png", Iso1: "TM", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "阿富汗", Alias: "Afghanistan", Code: "93", Icon: "/assets/country/afghanistan.png", Iso1: "AF", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "伊拉克", Alias: "Iraq", Code: "964", Icon: "/assets/country/iraq.png", Iso1: "IQ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "伊朗", Alias: "Iran", Code: "98", Icon: "/assets/country/iran.png", Iso1: "IR", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "叙利亚", Alias: "Syria", Code: "963", Icon: "/assets/country/syria.png", Iso1: "SY", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "约旦", Alias: "Jordan", Code: "962", Icon: "/assets/country/jordan.png", Iso1: "JO", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "黎巴嫩", Alias: "Lebanon", Code: "961", Icon: "/assets/country/lebanon.png", Iso1: "LB", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "以色列", Alias: "Israel", Code: "972", Icon: "/assets/country/israel.png", Iso1: "IL", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "巴勒斯坦", Alias: "Palestine", Code: "970", Icon: "/assets/country/palestine.png", Iso1: "PS", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "沙特阿拉伯", Alias: "SaudiArabia", Code: "966", Icon: "/assets/country/saudi_arabia.png", Iso1: "SA", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "巴林", Alias: "Bahrain", Code: "973", Icon: "/assets/country/bahrain.png", Iso1: "BH", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "卡塔尔", Alias: "Qatar", Code: "974", Icon: "/assets/country/qatar.png", Iso1: "QA", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "科威特", Alias: "Kuwait", Code: "965", Icon: "/assets/country/kuwait.png", Iso1: "KW", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "阿拉伯联合酋长国", Alias: "United Arab Emirates", Code: "971", Icon: "/assets/country/united_arab_emirates.png", Iso1: "AE", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "阿曼", Alias: "Oman", Code: "968", Icon: "/assets/country/oman.png", Iso1: "OM", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "也门", Alias: "Yemen", Code: "967", Icon: "/assets/country/yemen.png", Iso1: "YE", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "格鲁吉亚", Alias: "Georgia", Code: "995", Icon: "/assets/country/georgia.png", Iso1: "GE", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "亚美尼亚", Alias: "Armenia", Code: "374", Icon: "/assets/country/armenia.png", Iso1: "AM", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "阿塞拜疆", Alias: "Azerbaijan", Code: "994", Icon: "/assets/country/azerbaijan.png", Iso1: "AZ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "土耳其", Alias: "Turkey", Code: "90", Icon: "/assets/country/turkey.png", Iso1: "TR", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "塞浦路斯", Alias: "Cyprus", Code: "357", Icon: "/assets/country/cyprus.png", Iso1: "CY", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "英国", Alias: "England", Code: "44", Icon: "/assets/country/england.png", Iso1: "GB", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "爱尔兰", Alias: "Ireland", Code: "353", Icon: "/assets/country/ireland.png", Iso1: "IE", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "法国", Alias: "France", Code: "33", Icon: "/assets/country/france.png", Iso1: "FR", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "荷兰", Alias: "Netherlands", Code: "31", Icon: "/assets/country/netherlands.png", Iso1: "NL", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "比利时", Alias: "Belgium", Code: "32", Icon: "/assets/country/belgium.png", Iso1: "BE", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "卢森堡", Alias: "Luxembourg", Code: "352", Icon: "/assets/country/luxembourg.png", Iso1: "LU", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "摩纳哥", Alias: "Monaco", Code: "377", Icon: "/assets/country/monaco.png", Iso1: "MC", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "挪威", Alias: "Norway", Code: "47", Icon: "/assets/country/norway.png", Iso1: "NO", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "瑞典", Alias: "Sweden", Code: "46", Icon: "/assets/country/sweden.png", Iso1: "SE", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "芬兰", Alias: "Finland", Code: "358", Icon: "/assets/country/finland.png", Iso1: "FI", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "丹麦", Alias: "Denmark", Code: "45", Icon: "/assets/country/denmark.png", Iso1: "DK", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "冰岛", Alias: "Iceland", Code: "354", Icon: "/assets/country/iceland.png", Iso1: "IS", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "法罗群岛", Alias: "Faroe Islands", Code: "298", Icon: "/assets/country/faroese.png", Iso1: "FO", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "德国", Alias: "Germany", Code: "49", Icon: "/assets/country/germany.png", Iso1: "DE", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "波兰", Alias: "Poland", Code: "48", Icon: "/assets/country/poland.png", Iso1: "PL", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "捷克", Alias: "Czechia", Code: "420", Icon: "/assets/country/czech.png", Iso1: "CZ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "斯洛伐克", Alias: "Slovakia", Code: "421", Icon: "/assets/country/slovakia.png", Iso1: "SK", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "匈牙利", Alias: "Hungary", Code: "36", Icon: "/assets/country/hungary.png", Iso1: "HU", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "奥地利", Alias: "Austria", Code: "43", Icon: "/assets/country/austria.png", Iso1: "AT", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "列支敦士登", Alias: "Liechtenstein", Code: "423", Icon: "/assets/country/liechtenstein.png", Iso1: "LI", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "瑞士", Alias: "Switzerland", Code: "41", Icon: "/assets/country/switzerland.png", Iso1: "CH", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "俄罗斯", Alias: "Russia", Code: "7", Icon: "/assets/country/russia.png", Iso1: "RU", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "爱沙尼亚", Alias: "Estonia", Code: "372", Icon: "/assets/country/estonia.png", Iso1: "EE", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "拉脱维亚", Alias: "Latvia", Code: "371", Icon: "/assets/country/latvia.png", Iso1: "LV", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "立陶宛", Alias: "Lithuania", Code: "370", Icon: "/assets/country/lithuania.png", Iso1: "LT", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "白俄罗斯", Alias: "Belarus", Code: "375", Icon: "/assets/country/belarus.png", Iso1: "BY", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "乌克兰", Alias: "Ukraine", Code: "380", Icon: "/assets/country/ukraine.png", Iso1: "UA", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "摩尔多瓦", Alias: "Moldova", Code: "373", Icon: "/assets/country/moldova.png", Iso1: "MD", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "罗马尼亚", Alias: "Romania", Code: "40", Icon: "/assets/country/romania.png", Iso1: "RO", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "保加利亚", Alias: "Bulgaria", Code: "359", Icon: "/assets/country/bulgaria.png", Iso1: "BG", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "塞尔维亚", Alias: "Serbia", Code: "338", Icon: "/assets/country/serbia.png", Iso1: "RS", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "斯洛文尼亚", Alias: "Slovenia", Code: "386", Icon: "/assets/country/slovenia.png", Iso1: "SI", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "克罗地亚", Alias: "Croatia", Code: "385", Icon: "/assets/country/croatia.png", Iso1: "HR", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "波斯尼亚和黑塞哥维那", Alias: "Bosnia And Herzegovina", Code: "387", Icon: "/assets/country/bosnia_and_herzegovina.png", Iso1: "BA", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "马其顿", Alias: "Macedonia", Code: "389", Icon: "/assets/country/macedonia.png", Iso1: "MK", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "阿尔巴尼亚", Alias: "Albania", Code: "355", Icon: "/assets/country/albania.png", Iso1: "AL", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "希腊", Alias: "Greece", Code: "30", Icon: "/assets/country/greece.png", Iso1: "GR", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "意大利", Alias: "Italy", Code: "39", Icon: "/assets/country/italy.png", Iso1: "IT", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "圣马力诺", Alias: "San Marino", Code: "378", Icon: "/assets/country/san_marino.png", Iso1: "SM", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "梵蒂冈", Alias: "Vatican", Code: "379", Icon: "/assets/country/vatican.png", Iso1: "VA", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "葡萄牙", Alias: "Portugal", Code: "351", Icon: "/assets/country/portugal.png", Iso1: "PT", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "西班牙", Alias: "Spain", Code: "34", Icon: "/assets/country/spain.png", Iso1: "ES", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "安道尔", Alias: "Andorra", Code: "376", Icon: "/assets/country/andorra.png", Iso1: "AD", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "马耳他", Alias: "Malta", Code: "356", Icon: "/assets/country/malta.png", Iso1: "MT", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "埃及", Alias: "Egypt", Code: "20", Icon: "/assets/country/egypt.png", Iso1: "EG", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "利比亚", Alias: "Libya", Code: "218", Icon: "/assets/country/libya.png", Iso1: "LY", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "苏丹", Alias: "Sudan", Code: "249", Icon: "/assets/country/sudan.png", Iso1: "SD", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "突尼斯", Alias: "Tunisia", Code: "216", Icon: "/assets/country/tunisia.png", Iso1: "TN", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "阿尔及利亚", Alias: "Algeria", Code: "213", Icon: "/assets/country/algeria.png", Iso1: "DZ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "摩洛哥", Alias: "Morocco", Code: "212", Icon: "/assets/country/morocco.png", Iso1: "MA", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "埃塞俄比亚", Alias: "Ethiopia", Code: "251", Icon: "/assets/country/ethiopia.png", Iso1: "ET", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "厄立特里亚", Alias: "Eritrea", Code: "291", Icon: "/assets/country/eritrea.png", Iso1: "ER", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "索马里", Alias: "Somalia", Code: "252", Icon: "/assets/country/somalia.png", Iso1: "SO", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "吉布提", Alias: "Djibouti", Code: "253", Icon: "/assets/country/djibouti.png", Iso1: "DJ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "肯尼亚", Alias: "Kenya", Code: "254", Icon: "/assets/country/kenya.png", Iso1: "KE", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "坦桑尼亚", Alias: "Tanzania", Code: "255", Icon: "/assets/country/tasania.png", Iso1: "TZ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "乌干达", Alias: "Uganda", Code: "256", Icon: "/assets/country/uganda.png", Iso1: "UG", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "卢旺达", Alias: "Rwanda", Code: "250", Icon: "/assets/country/rwanda.png", Iso1: "RW", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "布隆迪", Alias: "Burundi", Code: "257", Icon: "/assets/country/burundi.png", Iso1: "BI", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "塞舌尔", Alias: "Seychelles", Code: "248", Icon: "/assets/country/seychelles.png", Iso1: "SC", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "乍得", Alias: "Chad", Code: "235", Icon: "/assets/country/chad.png", Iso1: "TD", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "中非", Alias: "Central Africa", Code: "236", Icon: "/assets/country/central_africa.png", Iso1: "CF", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "喀麦隆", Alias: "Cameroon", Code: "237", Icon: "/assets/country/cameroon.png", Iso1: "CM", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "赤道几内亚", Alias: "Equatorial Guinea", Code: "240", Icon: "/assets/country/equatorial_guinea.png", Iso1: "GQ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "加蓬", Alias: "Gabon", Code: "241", Icon: "/assets/country/gabon.png", Iso1: "GA", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "刚果", Alias: "Congo", Code: "242", Icon: "/assets/country/congo.png", Iso1: "CG", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "圣多美和普林西比", Alias: "Sao Tome And Principe", Code: "239", Icon: "/assets/country/sao_tome_and_principe.png", Iso1: "ST", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "毛里塔尼亚", Alias: "Mauritania", Code: "222", Icon: "/assets/country/mauritania.png", Iso1: "MR", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "塞内加尔", Alias: "Senegal", Code: "221", Icon: "/assets/country/senegal.png", Iso1: "SN", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "冈比亚", Alias: "Gambia", Code: "220", Icon: "/assets/country/gambia.png", Iso1: "GM", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "马里", Alias: "Mali", Code: "223", Icon: "/assets/country/mali.png", Iso1: "ML", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "布基纳法索", Alias: "Burkina Faso", Code: "226", Icon: "/assets/country/burkina_faso.png", Iso1: "BF", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "几内亚", Alias: "Guinea", Code: "224", Icon: "/assets/country/guinea.png", Iso1: "GN", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "几内亚比绍", Alias: "Guinea Bissau", Code: "245", Icon: "/assets/country/guinea_bissau.png", Iso1: "GW", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "佛得角", Alias: "Cape Verde", Code: "238", Icon: "/assets/country/cape_verde.png", Iso1: "CV", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "塞拉利昂", Alias: "Sierra Leone", Code: "232", Icon: "/assets/country/sierra_leone.png", Iso1: "SL", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "利比里亚", Alias: "Liberia", Code: "231", Icon: "/assets/country/liberia.png", Iso1: "LR", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "科特迪瓦", Alias: "Ivory Coast", Code: "225", Icon: "/assets/country/ivory_coast.png", Iso1: "CI", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "加纳", Alias: "Ghana", Code: "233", Icon: "/assets/country/ghana.png", Iso1: "GH", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "多哥", Alias: "Togo", Code: "228", Icon: "/assets/country/togo.png", Iso1: "TG", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "贝宁", Alias: "Benin", Code: "229", Icon: "/assets/country/benin.png", Iso1: "BJ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "尼日尔", Alias: "Niger", Code: "227", Icon: "/assets/country/niger.png", Iso1: "NE", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "尼日利亚", Alias: "Nigeria", Code: "234", Icon: "/assets/country/nigeria.png", Iso1: "NG", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "西撒哈拉", Alias: "WesternSahara", Code: "210", Icon: "/assets/country/western_sahara.png", Iso1: "EH", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "赞比亚", Alias: "Zambia", Code: "260", Icon: "/assets/country/zambia.png", Iso1: "ZM", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "安哥拉", Alias: "Angola", Code: "244", Icon: "/assets/country/angola.png", Iso1: "AO", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "津巴布韦", Alias: "Zimbabwe", Code: "263", Icon: "/assets/country/zimbabwe.png", Iso1: "ZW", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "马拉维", Alias: "Malawi", Code: "265", Icon: "/assets/country/malawi.png", Iso1: "MW", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "莫桑比克", Alias: "Mozambique", Code: "258", Icon: "/assets/country/mozambique.png", Iso1: "MZ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "博茨瓦纳", Alias: "Botswana", Code: "267", Icon: "/assets/country/botswana.png", Iso1: "BW", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "纳米比亚", Alias: "Namibia", Code: "264", Icon: "/assets/country/namibia.png", Iso1: "NA", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "南非", Alias: "SouthAfrica", Code: "27", Icon: "/assets/country/south_africa.png", Iso1: "ZA", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "斯威士兰", Alias: "Eswatini", Code: "268", Icon: "/assets/country/swaziland.png", Iso1: "SZ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "莱索托", Alias: "Lesotho", Code: "266", Icon: "/assets/country/Lesotho.png", Iso1: "LS", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "马达加斯加", Alias: "Madagascar", Code: "261", Icon: "/assets/country/madagascar.png", Iso1: "MG", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "科摩罗", Alias: "Comoros", Code: "269", Icon: "/assets/country/comoros.png", Iso1: "KM", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "毛里求斯", Alias: "Mauritius", Code: "230", Icon: "/assets/country/Mauritius.png", Iso1: "MU", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "圣赫勒拿岛", Alias: "Saint Helena", Code: "290", Icon: "/assets/country/st_helena.png", Iso1: "SH", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "马约特", Alias: "Mayotte", Code: "262", Icon: "/assets/country/mayotte.png", Iso1: "YT", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "加拿大", Alias: "Canada", Code: "1", Icon: "/assets/country/canada.png", Iso1: "CA", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "美国", Alias: "United States", Code: "1", Icon: "/assets/country/usa.png", Iso1: "US", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "墨西哥", Alias: "Mexico", Code: "52", Icon: "/assets/country/mexico.png", Iso1: "MX", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "格陵兰", Alias: "Greenland", Code: "299", Icon: "/assets/country/greenland.png", Iso1: "GL", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "圣皮埃尔和密克隆", Alias: "Saint Pierre and Miquelon", Code: "508", Icon: "/assets/country/saint_pierre_and_miquelon.png", Iso1: "PM", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "百慕大", Alias: "Bermuda", Code: "441", Icon: "/assets/country/bermuda.png", Iso1: "BM", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "危地马拉", Alias: "Guatemala", Code: "502", Icon: "/assets/country/guatemala.png", Iso1: "GT", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "伯利兹", Alias: "Belize", Code: "501", Icon: "/assets/country/belize.png", Iso1: "BZ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "萨尔瓦多", Alias: "Salvador", Code: "503", Icon: "/assets/country/salvador.png", Iso1: "SV", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "洪都拉斯", Alias: "Honduras", Code: "504", Icon: "/assets/country/honduras.png", Iso1: "HN", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "尼加拉瓜", Alias: "Nicaragua", Code: "505", Icon: "/assets/country/nicaragua.png", Iso1: "NI", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "哥斯达黎加", Alias: "CostaRica", Code: "506", Icon: "/assets/country/costa_rica.png", Iso1: "CR", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "巴拿马", Alias: "Panama", Code: "507", Icon: "/assets/country/panama.png", Iso1: "PA", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "巴哈马", Alias: "Bahamas", Code: "1242", Icon: "/assets/country/bahamas.png", Iso1: "BS", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "古巴", Alias: "Cuba", Code: "53", Icon: "/assets/country/cuba.png", Iso1: "CU", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "牙买加", Alias: "Jamaica", Code: "1876", Icon: "/assets/country/jamaica.png", Iso1: "JM", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "海地", Alias: "Haiti", Code: "509", Icon: "/assets/country/haiti.png", Iso1: "HT", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "多米尼加共和国", Alias: "Dominican Republic", Code: "1809", Icon: "/assets/country/dominica_republic.png", Iso1: "DO", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "安提瓜和巴布达", Alias: "Antigua And Barbuda", Code: "1268", Icon: "/assets/country/antigua_and_barbuda.png", Iso1: "AG", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "圣基茨和尼维斯", Alias: "Saint Kitts And Nevis", Code: "1869", Icon: "/assets/country/saint_kitts_and_nevis.png", Iso1: "KN", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "多米尼克", Alias: "Dominica", Code: "1767", Icon: "/assets/country/dominica.png", Iso1: "DM", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "圣卢西亚", Alias: "SaintLucia", Code: "1758", Icon: "/assets/country/saint_lucia.png", Iso1: "LC", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "圣文森特和格林纳丁斯", Alias: "Saint Vincent And The Grenadines", Code: "784", Icon: "/assets/country/saint_vincent_and_the_grenadines.png", Iso1: "VC", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "格林纳达", Alias: "Grenada", Code: "1473", Icon: "/assets/country/grenada.png", Iso1: "GD", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "巴巴多斯", Alias: "Barbados", Code: "1246", Icon: "/assets/country/barbados.png", Iso1: "BB", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "特立尼达和多巴哥", Alias: "Trinidad And Tobago", Code: "1868", Icon: "/assets/country/trinidad_and_tobago.png", Iso1: "TT", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "波多黎各", Alias: "Puerto Rico", Code: "1787", Icon: "/assets/country/puerto_rico.png", Iso1: "PR", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "英属维尔京群岛", Alias: "The British Virgin Islands", Code: "1284", Icon: "/assets/country/the_british_virgin_islands.png", Iso1: "VG", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "美属维尔京群岛", Alias: "United States Virgin Islands", Code: "1340", Icon: "/assets/country/united_states_virgin_islands.png", Iso1: "VI", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "安圭拉", Alias: "Anguilla", Code: "264", Icon: "/assets/country/anguilla.png", Iso1: "AI", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "蒙特塞拉特", Alias: "Montserrat", Code: "1664", Icon: "/assets/country/montserrat.png", Iso1: "MS", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "瓜德罗普", Alias: "Guadeloupe", Code: "590", Icon: "/assets/country/guadeloupe.png", Iso1: "GP", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "马提尼克", Alias: "Martinique", Code: "596", Icon: "/assets/country/martinique.png", Iso1: "MQ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "阿鲁巴", Alias: "Aruba", Code: "297", Icon: "/assets/country/aruba.png", Iso1: "AW", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "法属圣马丁", Alias: "Saint Martin", Code: "1721", Icon: "/assets/country/st_martin.png", Iso1: "MF", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "特克斯和凯科斯群岛", Alias: "Turks And Caicos Islands", Code: "1649", Icon: "/assets/country/turks_and_caicos_islands.png", Iso1: "TC", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "开曼群岛", Alias: "Cayman Islands", Code: "1345", Icon: "/assets/country/cayman_islands.png", Iso1: "KY", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "库拉索", Alias: "Curacao", Code: "5999", Icon: "/assets/country/curacao.png", Iso1: "CW", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "哥伦比亚", Alias: "Colombia", Code: "57", Icon: "/assets/country/colombia.png", Iso1: "CO", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "委内瑞拉", Alias: "Venezuela", Code: "58", Icon: "/assets/country/venezuela.png", Iso1: "VE", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "圭亚那", Alias: "Guyana", Code: "592", Icon: "/assets/country/guyana.png", Iso1: "GY", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "苏里南", Alias: "Suriname", Code: "597", Icon: "/assets/country/suriname.png", Iso1: "SR", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "法属圭亚那", Alias: "French Guiana", Code: "594", Icon: "/assets/country/french_guiana.png", Iso1: "GF", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "厄瓜多尔", Alias: "Ecuador", Code: "593", Icon: "/assets/country/ecuador.png", Iso1: "EC", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "秘鲁", Alias: "Peru", Code: "51", Icon: "/assets/country/peru.png", Iso1: "PE", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "玻利维亚", Alias: "Bolivia", Code: "591", Icon: "/assets/country/bolivia.png", Iso1: "BO", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "巴西", Alias: "Brazil", Code: "55", Icon: "/assets/country/brazil.png", Iso1: "BR", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "智利", Alias: "Chile", Code: "56", Icon: "/assets/country/chile.png", Iso1: "CL", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "阿根廷", Alias: "Argentina", Code: "54", Icon: "/assets/country/argentina.png", Iso1: "AR", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "乌拉圭", Alias: "Uruguay", Code: "598", Icon: "/assets/country/uruguay.png", Iso1: "UY", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "巴拉圭", Alias: "Paraguay", Code: "595", Icon: "/assets/country/paraguay.png", Iso1: "PY", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "澳大利亚", Alias: "Australia", Code: "61", Icon: "/assets/country/australia.png", Iso1: "AU", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "新西兰", Alias: "New Zealand", Code: "64", Icon: "/assets/country/new_zealand.png", Iso1: "NZ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "帕劳", Alias: "Palau", Code: "680", Icon: "/assets/country/palau.png", Iso1: "PW", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "密克罗尼西亚联邦", Alias: "Federated States Of Micronesia", Code: "691", Icon: "/assets/country/federated_states_of_micronesia.png", Iso1: "FM", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "马绍尔群岛", Alias: "Marshall Islands", Code: "692", Icon: "/assets/country/marshall_islands.png", Iso1: "MH", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "基里巴斯", Alias: "Kiribati", Code: "686", Icon: "/assets/country/kiribati.png", Iso1: "KI", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "瑙鲁", Alias: "Nauru", Code: "674", Icon: "/assets/country/nauru.png", Iso1: "NR", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "北马里亚纳", Alias: "Northern Mariana", Code: "670", Icon: "/assets/country/northern_mariana.png", Iso1: "MP", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "关岛", Alias: "Guam", Code: "1671", Icon: "/assets/country/guam.png", Iso1: "GU", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "巴布亚新几内亚", Alias: "Papua New Guinea", Code: "675", Icon: "/assets/country/papua_new_guinea.png", Iso1: "PG", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "所罗门群岛", Alias: "SolomonIslands", Code: "677", Icon: "/assets/country/solomon_islands.png", Iso1: "SB", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "瓦努阿图", Alias: "Vanuatu", Code: "678", Icon: "/assets/country/vanuatu.png", Iso1: "VU", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "斐济", Alias: "Fiji", Code: "679", Icon: "/assets/country/fiji.png", Iso1: "FJ", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "图瓦卢", Alias: "Tuvalu", Code: "688", Icon: "/assets/country/tuvalu.png", Iso1: "TV", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "萨摩亚", Alias: "Samoa", Code: "685", Icon: "/assets/country/samoa.png", Iso1: "WS", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "汤加", Alias: "Tonga", Code: "676", Icon: "/assets/country/tonga.png", Iso1: "TO", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "库克群岛", Alias: "Cook Islands", Code: "682", Icon: "/assets/country/island.png", Iso1: "CK", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "纽埃", Alias: "Niue", Code: "683", Icon: "/assets/country/niue.png", Iso1: "NU", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "托克劳", Alias: "Tokelau", Code: "690", Icon: "/assets/country/tokelau.png", Iso1: "TK", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "瓦利斯和富图纳", Alias: "Wallis And Futuna", Code: "681", Icon: "/assets/country/wallis_and_futuna.png", Iso1: "WF", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "皮特凯恩群岛", Alias: "Pitcairn Islands", Code: "649", Icon: "/assets/country/pitcairn_islands.png", Iso1: "PN", Sort: 99, Status: 10, Data: ""},
		{AdminId: adminsModel.SuperAdminId, Name: "美属萨摩亚", Alias: "American Samoa", Code: "684", Icon: "/assets/country/american_samoa.png", Iso1: "AS", Sort: 99, Status: 10, Data: ""},
	}
}
