package datas

import (
	"gofiber/app/models/model/adminsModel"
	"gofiber/app/models/model/types"
	"gofiber/app/models/model/walletsModel"
)

// InitWalletPayment 初始化钱包支付
func InitWalletPayment() []*walletsModel.WalletPayment {
	return []*walletsModel.WalletPayment{
		// 余额提现
		{AdminId: adminsModel.SuperAdminId, Name: "中国建设银行", Symbol: "USD", Icon: "/assets/icon/bank.png", Type: walletsModel.WalletPaymentTypeBank, Mode: walletsModel.WalletPaymentModeWithdraw, Data: []*walletsModel.WalletPaymentData{{Label: "bankName", Field: "name", IsShow: true}, {Label: "bankRealName", Field: "realName", IsShow: true}, {Label: "bankNumber", Field: "number", IsShow: true}, {Label: "bankCode", Field: "code", IsShow: true}, {Label: "bankRemark", Field: "remark", IsShow: true}}},
		{AdminId: adminsModel.SuperAdminId, Name: "美国摩根银行", Symbol: "USD", Icon: "/assets/icon/america.png", Type: walletsModel.WalletPaymentTypeBank, Mode: walletsModel.WalletPaymentModeWithdraw, Data: []*walletsModel.WalletPaymentData{{Label: "bankName", Field: "name", IsShow: true}, {Label: "bankRealName", Field: "realName", IsShow: true}, {Label: "bankNumber", Field: "number", IsShow: true}, {Label: "bankCode", Field: "code", IsShow: true}, {Label: "bankRemark", Field: "remark", IsShow: true}}},
		{AdminId: adminsModel.SuperAdminId, Name: "ERC20-USDT", Symbol: "USDT", Icon: "/assets/icon/usdt.png", Type: walletsModel.WalletPaymentTypeDigital, Mode: walletsModel.WalletPaymentModeWithdraw, Data: []*walletsModel.WalletPaymentData{{Label: "bankAddress", Field: "number", IsShow: true}}},
		{AdminId: adminsModel.SuperAdminId, Name: "ERC20-USDC", Symbol: "USDC", Icon: "/assets/icon/usdc.png", Type: walletsModel.WalletPaymentTypeDigital, Mode: walletsModel.WalletPaymentModeWithdraw, Data: []*walletsModel.WalletPaymentData{{Label: "bankAddress", Field: "number", IsShow: true}}},

		// 资产提现
		{AssetsId: 1, AdminId: adminsModel.SuperAdminId, Name: "ERC20-USDT", Symbol: "USDT", Icon: "/assets/icon/usdt.png", Type: walletsModel.WalletPaymentTypeDigital, Mode: walletsModel.WalletPaymentModeAssetsWithdraw, Data: []*walletsModel.WalletPaymentData{{Label: "bankAddress", Field: "number", IsShow: true}}},
		{AssetsId: 2, AdminId: adminsModel.SuperAdminId, Name: "ERC20-USDC", Symbol: "USDC", Icon: "/assets/icon/usdc.png", Type: walletsModel.WalletPaymentTypeDigital, Mode: walletsModel.WalletPaymentModeAssetsWithdraw, Data: []*walletsModel.WalletPaymentData{{Label: "bankAddress", Field: "number", IsShow: true}}},
		{AssetsId: 3, AdminId: adminsModel.SuperAdminId, Name: "ERC20-BTC", Symbol: "BTC", Icon: "/assets/icon/btc.png", Type: walletsModel.WalletPaymentTypeDigital, Mode: walletsModel.WalletPaymentModeAssetsWithdraw, Data: []*walletsModel.WalletPaymentData{{Label: "bankAddress", Field: "number", IsShow: true}}},
		{AssetsId: 4, AdminId: adminsModel.SuperAdminId, Name: "ERC20-ETH", Symbol: "EtH", Icon: "/assets/icon/eth.png", Type: walletsModel.WalletPaymentTypeDigital, Mode: walletsModel.WalletPaymentModeAssetsWithdraw, Data: []*walletsModel.WalletPaymentData{{Label: "bankAddress", Field: "number", IsShow: true}}},
		{AssetsId: 5, AdminId: adminsModel.SuperAdminId, Name: "ERC20-TRX", Symbol: "TRX", Icon: "/assets/icon/trx.png", Type: walletsModel.WalletPaymentTypeDigital, Mode: walletsModel.WalletPaymentModeAssetsWithdraw, Data: []*walletsModel.WalletPaymentData{{Label: "bankAddress", Field: "number", IsShow: true}}},

		// 余额充值
		{AdminId: adminsModel.SuperAdminId, Name: "DebitCard", Symbol: "USD", Icon: "/assets/icon/bank.png", Type: walletsModel.WalletPaymentTypeBank, Mode: walletsModel.WalletPaymentModeDeposit, Data: []*walletsModel.WalletPaymentData{{Label: "银行名称", Field: "name", Value: "建设银行", IsShow: true}, {Label: "真实姓名", Value: "隔壁老王", Field: "realName", IsShow: true}, {Label: "银行卡号", Field: "number", Value: "888866665555", IsShow: true}, {Label: "银行代码", Field: "code", Value: "xxx666", IsShow: true}}},
		{AdminId: adminsModel.SuperAdminId, Name: "BankOfAmerica", Symbol: "USD", Icon: "/assets/icon/america.png", Type: walletsModel.WalletPaymentTypeBank, Mode: walletsModel.WalletPaymentModeDeposit, Data: []*walletsModel.WalletPaymentData{{Label: "银行名称", Field: "name", Value: "建设银行", IsShow: true}, {Label: "真实姓名", Field: "realName", Value: "隔壁老王", IsShow: true}, {Label: "银行卡号", Field: "number", Value: "888866665555", IsShow: true}, {Label: "银行代码", Field: "code", Value: "xxx666", IsShow: true}}},
		{AdminId: adminsModel.SuperAdminId, Name: "ERC20-USDT", Symbol: "USDT", Icon: "/assets/icon/usdt.png", Type: walletsModel.WalletPaymentTypeDigital, Mode: walletsModel.WalletPaymentModeDeposit, Data: []*walletsModel.WalletPaymentData{{Label: "公链名称", Field: "name", Value: "ETH", IsShow: true}, {Label: "Token", Field: "realName", Value: "USDT", IsShow: true}, {Label: "地址", Field: "number", Value: "0x1Bdd1742C5dEd48bAa7F5D71dba59628D3A3130c", IsShow: true}}},
		{AdminId: adminsModel.SuperAdminId, Name: "ERC20-USDC", Symbol: "USDC", Icon: "/assets/icon/usdc.png", Type: walletsModel.WalletPaymentTypeDigital, Mode: walletsModel.WalletPaymentModeDeposit, Data: []*walletsModel.WalletPaymentData{{Label: "公链名称", Field: "name", Value: "ETH", IsShow: true}, {Label: "Token", Field: "realName", Value: "USDC", IsShow: true}, {Label: "地址", Field: "number", Value: "0x1Bdd1742C5dEd48bAa7F5D71dba59628D3A3130c", IsShow: true}}},
		{AdminId: adminsModel.SuperAdminId, Name: "xxx渠道", Symbol: "USD", Icon: "/assets/icon/bank.png", Type: walletsModel.WalletPaymentTypeChannel, IsVoucher: types.ModelBoolFalse, Mode: walletsModel.WalletPaymentModeDeposit, Data: []*walletsModel.WalletPaymentData{{Label: "渠道名称", Field: "name", Value: "xx渠道余额", IsShow: false}, {Label: "渠道标识", Field: "realName", Value: "es", IsShow: false}, {Label: "渠道ID", Field: "number", Value: "1", IsShow: false}}},

		// 资产充值
		{AssetsId: 1, AdminId: adminsModel.SuperAdminId, Name: "ERC20-USDT", Symbol: "USDT", Icon: "/assets/icon/usdt.png", Type: walletsModel.WalletPaymentTypeDigital, Mode: walletsModel.WalletPaymentModeAssetsDeposit, Data: []*walletsModel.WalletPaymentData{{Label: "公链名称", Field: "name", Value: "ETH", IsShow: true}, {Label: "Token", Field: "realName", Value: "USDT", IsShow: true}, {Label: "地址", Field: "number", Value: "0x1Bdd1742C5dEd48bAa7F5D71dba59628D3A3130c", IsShow: true}}},
		{AssetsId: 2, AdminId: adminsModel.SuperAdminId, Name: "ERC20-USDC", Symbol: "USDC", Icon: "/assets/icon/usdc.png", Type: walletsModel.WalletPaymentTypeDigital, Mode: walletsModel.WalletPaymentModeAssetsDeposit, Data: []*walletsModel.WalletPaymentData{{Label: "公链名称", Field: "name", Value: "ETH", IsShow: true}, {Label: "Token", Field: "realName", Value: "USDC", IsShow: true}, {Label: "地址", Field: "number", Value: "0x1Bdd1742C5dEd48bAa7F5D71dba59628D3A3130c", IsShow: true}}},
		{AssetsId: 3, AdminId: adminsModel.SuperAdminId, Name: "ERC20-BTC", Symbol: "BTC", Icon: "/assets/icon/btc.png", Type: walletsModel.WalletPaymentTypeDigital, Mode: walletsModel.WalletPaymentModeAssetsDeposit, Data: []*walletsModel.WalletPaymentData{{Label: "公链名称", Field: "name", Value: "ETH", IsShow: true}, {Label: "Token", Field: "realName", Value: "BTC", IsShow: true}, {Label: "地址", Field: "number", Value: "0x1Bdd1742C5dEd48bAa7F5D71dba59628D3A3130c", IsShow: true}}},
		{AssetsId: 4, AdminId: adminsModel.SuperAdminId, Name: "ERC20-ETH", Symbol: "ETH", Icon: "/assets/icon/eth.png", Type: walletsModel.WalletPaymentTypeDigital, Mode: walletsModel.WalletPaymentModeAssetsDeposit, Data: []*walletsModel.WalletPaymentData{{Label: "公链名称", Field: "name", Value: "ETH", IsShow: true}, {Label: "Token", Field: "realName", Value: "ETH", IsShow: true}, {Label: "地址", Field: "number", Value: "0x1Bdd1742C5dEd48bAa7F5D71dba59628D3A3130c", IsShow: true}}},
		{AssetsId: 5, AdminId: adminsModel.SuperAdminId, Name: "ERC20-TRX", Symbol: "TRX", Icon: "/assets/icon/trx.png", Type: walletsModel.WalletPaymentTypeDigital, Mode: walletsModel.WalletPaymentModeAssetsDeposit, Data: []*walletsModel.WalletPaymentData{{Label: "公链名称", Field: "name", Value: "ETH", IsShow: true}, {Label: "Token", Field: "realName", Value: "TRX", IsShow: true}, {Label: "地址", Field: "number", Value: "0x1Bdd1742C5dEd48bAa7F5D71dba59628D3A3130c", IsShow: true}}},
	}
}
