package datas

import (
	"gofiber/app/models/model/adminsModel"
	"gofiber/app/models/model/systemsModel"
	"gofiber/app/models/model/walletsModel"
)

// InitTranslate 初始化翻译表
func InitTranslate() []*systemsModel.Translate {
	data := make([]*systemsModel.Translate, 0)
	// 系统翻译
	data = append(data, []*systemsModel.Translate{
		// 公用翻译
		{AdminId: 0, Lang: "zh-CN", Name: "验证参数不能为空", Field: "required", Value: "%s 参数不能为空 %s"},
		{AdminId: 0, Lang: "zh-CN", Name: "验证参数min", Field: "min", Value: "%s 参数最小值为 %s"},
		{AdminId: 0, Lang: "zh-CN", Name: "验证参数max", Field: "max", Value: "%s 参数最大值为 %s"},
		{AdminId: 0, Lang: "zh-CN", Name: "验证参数oneof", Field: "oneof", Value: "%s 范围不匹配｜必须 %s"},
		{AdminId: 0, Lang: "zh-CN", Name: "验证参数大于", Field: "gt", Value: "%s 必须大于 %s"},
		{AdminId: 0, Lang: "zh-CN", Name: "验证参数大于等于", Field: "gte", Value: "%s 必须大于等于 %s"},
		{AdminId: 0, Lang: "zh-CN", Name: "验证参数小于", Field: "lt", Value: "%s 必须小于 %s"},
		{AdminId: 0, Lang: "zh-CN", Name: "验证参数小于等于", Field: "lte", Value: "%s 必须小于等于 %s"},
		{AdminId: 0, Lang: "zh-CN", Name: "验证参数数字和字符串", Field: "alphanum", Value: "%s 必须为字符串或数字 %s"},

		// 商户接口翻译
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "余额不足", Field: "insufficientBalance", Value: "余额不足"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "资产不足", Field: "insufficientAssets", Value: "资产不足"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "操作异常", Field: "abnormalOperation", Value: "操作异常 | %v"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "验证码错误", Field: "codeError", Value: "验证码错误"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "账户已存在", Field: "accountAlreadyExists", Value: "账户已存在"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "账户或密码错误", Field: "usernameOrPasswordIncorrect", Value: "账户或密码错误"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "安全密钥不正确", Field: "incorrectSecurityKey", Value: "安全密钥不正确"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "旧密码不正确", Field: "theOldPasswordIsIncorrect", Value: "旧密码不正确"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "超出限制", Field: "limitExceeded", Value: "超出限制 | %v"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "范围不匹配", Field: "rangeMismatch", Value: "范围不匹配 | %v - %v"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "不能为空", Field: "notBeEmpty", Value: "不能为空"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "查找错误", Field: "findError", Value: "查找错误"},

		// 商户前台翻译
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "充值提示详情", Field: "depositDesc", Value: "充值注意事项"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "提现提示详情", Field: "withdrawDesc", Value: "提现注意事项"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "支付凭证", Field: "paymentVoucher", Value: "支付凭证"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "数字货币", Field: "digitalCurrency", Value: "数字货币"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "银行名称", Field: "bankName", Value: "银行名称"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "真实姓名", Field: "bankRealName", Value: "真实姓名"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "银行卡号", Field: "bankNumber", Value: "银行卡号"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "银行代码", Field: "bankCode", Value: "银行代码"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "备注信息", Field: "bankRemark", Value: "备注信息"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "数字地址", Field: "bankAddress", Value: "数字地址"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "站点介绍", Field: "siteIntroduce", Value: " "},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "站点通知", Field: "siteNotice", Value: " "},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "首页", Field: "tab_home", Value: "首页"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "行情", Field: "tab_markets", Value: "市场"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "合约", Field: "tab_contract", Value: "合约"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "期货", Field: "tab_futures", Value: "期货"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "我的", Field: "tab_user", Value: "我的"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "数字货币行情", Field: "digitalMarkets", Value: "数字货币行情"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "外汇行情", Field: "forexMarkets", Value: "外汇行情"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "期货行情", Field: "futuresMarkets", Value: "期货行情"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "钱包管理", Field: "walletsManage", Value: "钱包管理"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "钱包账单", Field: "walletsBill", Value: "钱包账单"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "余额账单", Field: "balanceBill", Value: "余额账单"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "资产账单", Field: "assetsBill", Value: "资产账单"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "我的钱包", Field: "userWallets", Value: "我的钱包"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "提现账户", Field: "withdrawAccount", Value: "提现账户"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "我的资产", Field: "userAssets", Value: "我的资产"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "转移记录", Field: "transferRecord", Value: "转移记录"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "转换记录", Field: "convertRecord", Value: "转换记录"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "团队管理", Field: "teamManage", Value: "团队管理"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "我的团队", Field: "userTeam", Value: "我的团队"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "团队收益", Field: "userEarnings", Value: "我的收益"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "邀请好友", Field: "userInvite", Value: "邀请好友"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "邀请好友副标题", Field: "inviteFriendsSmall", Value: "邀请你的好友, 领取收益."},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "服务管理", Field: "serviceManage", Value: "服务管理"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "会员权益", Field: "userLevel", Value: "会员权益"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "实名认证", Field: "userAuth", Value: "实名认证"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "帮助中心", Field: "helpers", Value: "帮助中心"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "偏好设置", Field: "settings", Value: "偏好设置"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "下载中心", Field: "download", Value: "下载中心"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "下载中心副标题", Field: "downloadSmall", Value: "下载APP能更好的体验, 欢迎使用手机软件体验。"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "余额充值", Field: "deposit", Value: "余额充值"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "资产充值", Field: "assetsDeposit", Value: "资产充值"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "余额提现", Field: "withdraw", Value: "余额提现"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "资产提现", Field: "assetsWithdraw", Value: "资产提现"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "资金转移", Field: "transfer", Value: "资金转移"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "余额转移", Field: "balanceTransfer", Value: "余额转移"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "资产转移", Field: "assetsTransfer", Value: "资产转移"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "资金转换", Field: "convert", Value: "资金转换"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "切换语言", Field: "switchLang", Value: "切换语言"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "关于", Field: "about", Value: "关于"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "产品", Field: "product", Value: "产品"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "服务", Field: "service", Value: "服务"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "帮助", Field: "helper", Value: "帮助"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "社交", Field: "social", Value: "社交"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "关于我们", Field: "aboutUs", Value: "关于我们"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "账户", Field: "username", Value: "账户"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "头像", Field: "avatar", Value: "头像"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "昵称", Field: "nickname", Value: "昵称"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "性别", Field: "sex", Value: "性别"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "生日", Field: "birthday", Value: "生日"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "密码", Field: "password", Value: "密码"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "验证码", Field: "code", Value: "验证码"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "登录", Field: "login", Value: "登录"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "登录副标题", Field: "loginSmall", Value: "登录您的账户, 开启旅程～"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "忘记密码", Field: "forgotPassword", Value: "忘记密码?"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "未注册去登录", Field: "toRegister", Value: "还没有账户, 去注册!"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "注册", Field: "register", Value: "注册"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "注册副标题", Field: "registerSmall", Value: "创建您的账户, 开启旅程~"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "已有账户去登录", Field: "toLogin", Value: "已有账户, 现在去登录!"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "确认密码", Field: "cmfPassword", Value: "确认密码"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "邀请码", Field: "inviteCode", Value: "邀请码"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "安全密钥", Field: "secretKey", Value: "安全密钥"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "输入安全密钥", Field: "enterSecretKey", Value: "请输入安全密钥"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "邮箱", Field: "email", Value: "邮箱地址"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "手机号码", Field: "telephone", Value: "手机号码"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "确认安全密钥", Field: "cmfSecretKey", Value: "确认安全密钥"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "退出登录", Field: "logout", Value: "退出登录"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "退出登录副标题", Field: "logoutSmall", Value: "您确定要退出登录吗?"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "两次密码不一致", Field: "twoPasswordsAreDifferent", Value: "两次密码不一致"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "两次安全密钥不一致", Field: "twoSecretKeyAreDifferent", Value: "两次安全密钥不一致"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "会员", Field: "member", Value: "会员"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "用户设置", Field: "userSettings", Value: "用户设置"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "立即获取", Field: "buyLevel", Value: "立即获取"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "已经购买", Field: "purchased", Value: "已经购买"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "是否购买", Field: "isBuy", Value: "是否确定购买"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "不能购买低于当前等级", Field: "lowerLevel", Value: "不能购买低于当前等级"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "证件名称", Field: "idName", Value: "证件名称"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "证件号码", Field: "idNumber", Value: "证件号码"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "证件地址", Field: "idAddress", Value: "证件地址"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "证件照正面", Field: "idPhoto1", Value: "证件照正面"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "证件照反面", Field: "idPhoto2", Value: "证件照反面"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "手持证件照", Field: "idPhoto3", Value: "手持证件照"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "证件凭证", Field: "idPhoto", Value: "证件凭证"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "账户信息", Field: "accountInfo", Value: "账户信息"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "收款地址", Field: "addressInfo", Value: "收款地址"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "更新登录密码", Field: "updatePassword", Value: "更新登录密码"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "旧密码", Field: "oldPassword", Value: "旧密码"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "新密码", Field: "newPassword", Value: "新密码"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "旧安全密钥", Field: "oldSecretKey", Value: "旧安全密钥"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "新安全密钥", Field: "newSecretKey", Value: "新安全密钥"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "更新安全密钥", Field: "updateSecretKey", Value: "更新安全密钥"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "绑定手机号码", Field: "bindTelephone", Value: "绑定手机号码"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "消息通知", Field: "notice", Value: "消息通知"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "版本信息", Field: "version", Value: "版本信息"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "会员权益说明", Field: "levelSmall", Value: "获取更多的权益体验～"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "帮助中心标题", Field: "helperTitle", Value: "平台帮助文档, 如果有其他问题请联系在线客服~"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "7x24小时", Field: "24hour", Value: "7x24小时服务"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "邀请人数", Field: "inviteNums", Value: "邀请人数"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "今日充值", Field: "todayDeposit", Value: "今日充值"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "总充值", Field: "totalDeposit", Value: "总充值"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "今日收益", Field: "todayEarnings", Value: "今日收益"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "总收益", Field: "totalEarnings", Value: "总收益"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "今日邀请", Field: "todayInvite", Value: "今日邀请"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "总邀请", Field: "totalInvite", Value: "总邀请"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "请输入金额", Field: "enterMoney", Value: "请输入金额"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "请输入对方账户", Field: "enterUserName", Value: "请输入对方账户"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "没有绑定提现账户", Field: "notBindWithdrawAccount", Value: "没有绑定提现账户"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "确认兑换", Field: "confirmRedemption", Value: "确认兑换"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "接收", Field: "receive", Value: "接收"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "汇率", Field: "ratio", Value: "汇率"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "立即实名", Field: "nowAuth", Value: "立即实名"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "实名成功", Field: "successAuth", Value: "实名成功"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "实名审核", Field: "pendingAuth", Value: "实名审核"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "实名失败", Field: "failedAuth", Value: "实名失败"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "信用分", Field: "creditScore", Value: "信用分"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "成功", Field: "success", Value: "成功"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "失败", Field: "error", Value: "失败"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "货币单位", Field: "currency", Value: "$"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "取消", Field: "cancel", Value: "取消"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "确定", Field: "confirm", Value: "确定"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "刷新", Field: "refresh", Value: "刷新"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "删除", Field: "delete", Value: "删除"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "新增", Field: "create", Value: "新增"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "编辑", Field: "edit", Value: "编辑"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "详情", Field: "desc", Value: "详情"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "查看", Field: "views", Value: "查看"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "复制", Field: "copy", Value: "复制"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "更多", Field: "more", Value: "更多"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "查询", Field: "search", Value: "查询"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "提交", Field: "submit", Value: "提交"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "重新提交", Field: "reSubmit", Value: "重新提交"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "完成", Field: "complete", Value: "完成"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "审核", Field: "pending", Value: "审核"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "拒绝", Field: "refuse", Value: "拒绝"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "筛选", Field: "filter", Value: "筛选"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "类型", Field: "type", Value: "类型"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "时间范围", Field: "betweenTime", Value: "时间范围"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "暂无数据", Field: "noData", Value: "暂无数据"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "男", Field: "male", Value: "男"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "未知", Field: "unknown", Value: "未知"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "女", Field: "female", Value: "女"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "统计", Field: "statistics", Value: "统计"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "记录", Field: "record", Value: "记录"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "余额", Field: "balance", Value: "余额"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "手续费", Field: "fee", Value: "手续费"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "可用余额", Field: "availableBalance", Value: "可用余额"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "可用资产", Field: "availableAssets", Value: "可用资产"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "可用", Field: "usable", Value: "可用"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "转移账户", Field: "transferUserName", Value: "转移账户"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "资产", Field: "assets", Value: "资产"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "总资产", Field: "totalAssets", Value: "总资产"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "资产分布", Field: "assetsBlock", Value: "资产分布"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "币种", Field: "currencies", Value: "币种"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "金额", Field: "money", Value: "金额"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "凭证", Field: "proof", Value: "凭证"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "全部", Field: "all", Value: "全部"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "注册时间", Field: "registerTime", Value: "注册时间"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "去设置", Field: "gotoSetting", Value: "去设置"},

		// 项目翻译, 文章翻译
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "分类1", Field: "category1", Value: "分类1"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "分类1子级1", Field: "category1child1", Value: "分类1子级1"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "分类1子级2", Field: "category1child2", Value: "分类1子级2"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "分类2", Field: "category2", Value: "分类1"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "分类2子级1", Field: "category2child1", Value: "分类2子级1"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "分类2子级2", Field: "category2child2", Value: "分类2子级2"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "关于我们内容", Field: "aboutUsContent", Value: "欢迎来到BTCCRY  Btccry相信，无论你是谁，无论你来自哪里，每个人都应享有赚取、持有、消费、分享和赠予财富的自由。"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "服务条款", Field: "serviceAgreement", Value: "服务条款"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "服务条款内容", Field: "serviceAgreementContent", Value: "本条款构成您（“您”、“您的”）与Btccry（“Btccry”、“我们”、“我们的”）之间具有法律约束力的协议。您在使用平台提供、通过平台提供或以其他方式向您提供的Btccry服务时适用本条款。Btccry服务可能由Btccry提供，也可能按照本条款、任何产品条款或任何附加条款的规定由任何Btccry联盟伙伴提供。 您注册Btccry账户、访问Btccry平台和/或使用Btccry服务即表明，您同意您已经阅读、理解并接受本条款及其中提及的任何附加文件或条款。您承认并同意您将受本条款不时更新及修订后版本约束并遵守其规定。 如果您未完全理解并接受本条款，请勿注册Btccry账户，也不要访问或使用平台或任何Btccry服务。"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "隐私保护", Field: "privacyPolicy", Value: "隐私保护"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "隐私保护内容", Field: "privacyPolicyContent", Value: "欢迎来到我们的隐私门户。 我们创建此页面是为了帮助您浏览我们的隐私计划的关键方面，并了解有关您的隐私权的更多信息。 在 Btccry，我们致力于保护您的隐私和数据。 您的个人信息的安全对我们至关重要，我们遵循严格的内部准则、法律要求和行业最佳实践，以确保您的数据安全并仅用于授权目的。"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "免责声明", Field: "disclaimer", Value: "免责声明"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "免责声明内容", Field: "disclaimerContent", Value: "免责声明内容"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "重置密码", Field: "helperLabel1", Value: "重置密码"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "重置密码内容", Field: "helperContent1", Value: "如果您忘记了密码，可以轻松重设。 请在登入页面点击“忘记密码？”链接，然后告诉客户支援团队你忘了密码并根据客户支援团队的指示，您就可以获得被重置后的密码。 为了确保帐户安全，请确保您的新密码足够复杂，且不与其他网站共用相同密码。 如果在重设密码过程中遇到任何问题，欢迎联络我们的客户支援团队以取得协助。"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "安全建议", Field: "helperLabel2", Value: "安全建议"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "安全建议内容", Field: "helperContent2", Value: "为了保护您的账户安全，我们建议您采取以下措施：首先，使用强密码，结合大写字母、小写字母、数字和特殊符号。 其次，定期更换密码，避免使用相同的密码登录不同网站。 此外，启用两因素认证（2FA）增加额外的安全层。 请勿在公共计算机或不安全的网络环境中登录账户，并始终保持您的个人信息和联系方式更新。 最后，警惕任何可疑的邮件或信息，避免点击不明链接或分享敏感信息。"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "取消订阅", Field: "helperLabel3", Value: "取消订阅"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "取消订阅内容", Field: "helperContent3", Value: "取消订阅非常简单。 登录您的账户后，前往账户设置页面，在那里您会找到「订阅管理」选项。 选择您想要取消的服务，并点击「取消订阅」按钮。 根据您的订阅类型，可能会有一段提前通知期。 请注意，取消订阅可能会影响到您享受的某些服务或优惠。 如果您在取消订阅过程中遇到任何问题或需要进一步的帮助，欢迎随时联系我们的客户服务团队。"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "产品服务", Field: "productLabel1", Value: "产品服务"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "产品服务内容", Field: "productContent1", Value: "欢迎来到我们的交易平台！ 我们致力于为您提供安全、高效、多样化的交易体验。 无论您是初学者还是经验丰富的交易者，我们都为您提供了丰富的产品和服务，以满足您的需求。 特点包括多样化的交易对、严格的安全措施、高性能的交易引擎、用户友好的界面、广泛的教育资源，以及全天候客户支持。 我们的承诺是透明度、创新、社区参与，以及回馈我们的忠实用户。 加入我们，开始您的交易之旅吧！"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "基础和专业方案", Field: "productLabel2", Value: "基础和专业方案"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "基础和专业方案内容", Field: "productContent2", Value: "我们的平台提供基础和专业方案，以适应各种用户需求。 基础方案包括注册和账户管理、市场浏览和有限的交易功能。 专业方案，价格为每月9.99美元，提供全面的交易功能、进阶图表和分析工具、优先客户支持，以及额外的教育资源。 我们还为机构和专业交易者提供定制化解决方案，称为企业方案。 我们的定价灵活、透明，旨在满足我们用户群的多样化需求。"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "新产品介绍", Field: "productLabel3", Value: "新产品介绍"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "新产品介绍内容", Field: "productContent3", Value: "我们自豪地推出「数字资产投资组合优化工具」，旨在帮助投资者最大化投资回报并降低风险。 此工具提供智能投资组合优化、动态资产配置、风险管理与模拟测试，以及个性化建议和报告。 用户可以快速注册，输入他们的投资偏好，并接收优化的投资组合推荐。 我们承诺提供更智能、更高效的投资解决方案，带来卓越的用户体验。"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "什么是加密货币交易平台", Field: "article1", Value: "什么是加密货币交易平台？"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "什么是加密货币交易平台内容", Field: "articleContent1", Value: "加密货币交易平台是供用户买卖加密货币的数字市场，用户可以在这些平台上买卖比特币、以太币和泰达币等币种。币安交易平台是全球交易量最大的加密货币交易平台。 "},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "什么是数字货币", Field: "article2", Value: "什么是数字货币"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "什么是数字货币内容", Field: "articleContent2", Value: "数字货币是一种基于区块链技术的去中心化数字资产，具有高度透明、支持无边界交易和不可篡改等几大特性。目前，市值最大的数字货币依次是比特币、以太币和泰达币，均可在BTCCRY平台进行交易。"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "如何在购买比特币和其他加密货币", Field: "article3", Value: "如何在购买比特币和其他加密货币"},
		{AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "如何在购买比特币和其他加密货币内容", Field: "articleContent3", Value: "用户可通过多种方式在BTCCRY买入加密货币。您可以使用信用卡/借记卡、现金余额或Apple Pay/Google Pay在BTCCRY上买币。开始买币之前，请确保您已完成BTCCRY账户身份认证。"},
	}...)

	// 钱包账单翻译
	for _, billTypeInfo := range walletsModel.WalletUserBillTypeList {
		data = append(data, &systemsModel.Translate{
			Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: billTypeInfo.Label,
			Field: billTypeInfo.Field, Value: billTypeInfo.Label,
		})
	}
	// 前台追加翻译
	data = append(data, []*systemsModel.Translate{
		// 分类翻译
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "女装与时尚", Field: "womenWearAndFashion", Value: "女装与时尚"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "女装", Field: "womenWear", Value: "女装"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "裙子", Field: "dress", Value: "裙子"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "女士T恤", Field: "womenTShirt", Value: "女士T恤"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "女士衬衫", Field: "womenShirt", Value: "女士衬衫"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "外套", Field: "coat", Value: "外套"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "女士牛仔裤", Field: "womenJeans", Value: "女士牛仔裤"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "女士配件", Field: "womenAccessories", Value: "女士配件"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "女士帽子", Field: "womenHat", Value: "女士帽子"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "女士围巾", Field: "womenScarf", Value: "女士围巾"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "女士袜子", Field: "womenSocks", Value: "女士袜子"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "男装与时尚", Field: "menWearAndFashion", Value: "男装与时尚"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "男装", Field: "menWear", Value: "男装"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "男士T恤", Field: "menTShirt", Value: "男士T恤"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "夹克", Field: "jacket", Value: "夹克"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "男士牛仔裤", Field: "menJeans", Value: "男士牛仔裤"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "男士衬衫", Field: "menShirt", Value: "男士衬衫"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "西装", Field: "suit", Value: "西装"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "男士配件", Field: "menAccessories", Value: "男士配件"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "男士帽子", Field: "menHat", Value: "男士帽子"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "男士围巾", Field: "menScarf", Value: "男士围巾"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "男士袜子", Field: "menSocks", Value: "男士袜子"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "电脑与配件", Field: "computersAndAccessories", Value: "电脑与配件"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "台式机与一体机", Field: "desktopAndAllInOne", Value: "台式机与一体机"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "一体机", Field: "allInOne", Value: "一体机"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "主机", Field: "host", Value: "主机"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "台式整机", Field: "desktopMachine", Value: "台式整机"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "笔记本", Field: "notebook", Value: "笔记本"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "鼠标", Field: "mouse", Value: "鼠标"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "键盘", Field: "keyboard", Value: "键盘"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "网络配置", Field: "networkEquipment", Value: "网络配置"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "路由器", Field: "router", Value: "路由器"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "打印服务器", Field: "printServer", Value: "打印服务器"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "中继器", Field: "concentrator", Value: "中继器"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "食品饮料", Field: "foodAndBeverage", Value: "食品饮料"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "食品", Field: "food", Value: "食品"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "糖果", Field: "candies", Value: "糖果"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "果冻布丁", Field: "jellyPudding", Value: "果冻布丁"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "坚果炒货", Field: "roastedNuts", Value: "坚果炒货"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "肉类零食", Field: "meatSnack", Value: "肉类零食"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "膨化食品", Field: "puffedFood", Value: "膨化食品"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "果干蜜饯", Field: "driedFruitPreserves", Value: "果干蜜饯"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "酒水茶饮", Field: "wineAndTea", Value: "酒水茶饮"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "果茶", Field: "nectar", Value: "果茶"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "酒水", Field: "wine", Value: "酒水"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "可乐", Field: "cola", Value: "可乐"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "母婴玩具", Field: "babyToy", Value: "母婴玩具"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "婴幼玩具", Field: "toddlersToy", Value: "婴幼玩具"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "游戏垫", Field: "playMat", Value: "游戏垫"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "摇摇车", Field: "kiddieRide", Value: "摇摇车"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "浴室玩具", Field: "bathToy", Value: "浴室玩具"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "敲击玩具", Field: "percussionToy", Value: "敲击玩具"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "木马摇马", Field: "rockingHorse", Value: "木马摇马"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "游戏屋", Field: "playTent", Value: "游戏屋"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "毛绒布艺", Field: "plushFabric", Value: "毛绒布艺"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "毛绒木偶", Field: "plushPuppet", Value: "毛绒木偶"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "毛绒收纳", Field: "plushStorage", Value: "毛绒收纳"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "毛绒背包", Field: "plushBackpack", Value: "毛绒背包"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "运动及户外", Field: "sportsAndOutdoor", Value: "运动及户外"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "运动户外", Field: "sportsOutdoors", Value: "运动户外"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "冲浪服", Field: "surfingWetsuit", Value: "冲浪服"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "篮球服", Field: "basketballClothes", Value: "篮球服"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "瑜伽服", Field: "yogaClothes", Value: "瑜伽服"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "登山鞋", Field: "climbingBoot", Value: "登山鞋"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "登山杖", Field: "alpenstock", Value: "登山杖"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "户外运动包", Field: "outdoorSportsBag", Value: "户外运动包"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "登山包", Field: "campingBag", Value: "登山包"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "健身包", Field: "gymBag", Value: "健身包"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "装备包", Field: "equipmentPack", Value: "装备包"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "健身训练", Field: "fitness", Value: "健身训练"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "护具", Field: "protectiveClothing", Value: "护具"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "电子设备", Field: "electronicEquipment", Value: "电子设备"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "家居生活", Field: "homeLife", Value: "家居生活"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "床上用品", Field: "beddings", Value: "床上用品"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "枕头枕芯", Field: "pillowCore", Value: "枕头枕芯"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "被子", Field: "quilt", Value: "被子"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "床垫", Field: "mattress", Value: "床垫"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "四件套", Field: "fourPieceSet", Value: "四件套"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "生活用品", Field: "articlesOfDailyUse", Value: "生活用品"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "毛巾浴巾", Field: "towelBath", Value: "毛巾浴巾"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "拖鞋", Field: "slipper", Value: "拖鞋"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "马桶刷", Field: "toiletBrush", Value: "马桶刷"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "珠宝及手表", Field: "jeweleryAndWatches", Value: "珠宝及手表"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "女士珠宝饰品", Field: "womenJeweleryAccessories", Value: "女士珠宝饰品"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "戒指", Field: "ring", Value: "戒指"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "手链", Field: "bracelet", Value: "手链"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "项链", Field: "necklace", Value: "项链"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "发饰", Field: "hairAccessory", Value: "发饰"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "珍珠饰品", Field: "pearlAccessories", Value: "珍珠饰品"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "耳饰", Field: "earring", Value: "耳饰"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "饰品配件", Field: "jewelryAccessory", Value: "饰品配件"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "首饰盒", Field: "jewelCase", Value: "首饰盒"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "饰品清洁", Field: "jewelryCleaning", Value: "饰品清洁"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "裸钻", Field: "looseDiamond", Value: "裸钻"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "手机数码", Field: "mobilePhoneNumber", Value: "手机数码"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "手机通讯", Field: "mobilePhoneCommunication", Value: "手机通讯"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "手机", Field: "cellPhone", Value: "手机"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "SIM卡工具", Field: "simToolkit", Value: "SIM卡工具"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "手机配件", Field: "mobilePhoneSpareParts", Value: "手机配件"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "耳机", Field: "earphone", Value: "耳机"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "手机膜", Field: "phoneScreenFilm", Value: "手机膜"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "自拍杆", Field: "selfieStick", Value: "自拍杆"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "手机壳", Field: "protectiveContainment", Value: "手机壳"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "手机镜头", Field: "mobilePhoneLens", Value: "手机镜头"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "充电器", Field: "charger", Value: "充电器"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "美容化妆", Field: "cosmetics", Value: "美容化妆"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "面部护肤", Field: "facialSkinCare", Value: "面部护肤"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "面膜", Field: "facialMask", Value: "面膜"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "面霜乳液", Field: "creamLotion", Value: "面霜乳液"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "精华", Field: "essence", Value: "精华"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "面部清洁", Field: "facialCleansing", Value: "面部清洁"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "防晒霜", Field: "sunCream", Value: "防晒霜"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "润唇膏", Field: "lipPomade", Value: "润唇膏"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "美发护肤", Field: "hairAndSkinCare", Value: "美发护肤"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "洗发", Field: "liquidShampoo", Value: "洗发"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "染发", Field: "hairDyeLiquid", Value: "染发"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "护发", Field: "hairConditioner", Value: "护发"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "账单类型[商家采购产品]", Field: "WalletUserBillTypePurchaseProduct", Value: "商家采购商品"},

		// 前台翻译
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "分类", Field: "tab_category", Value: "分类"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "购物车", Field: "tab_shopping", Value: "购物车"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "消息", Field: "tab_message", Value: "消息"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "我的", Field: "tab_user", Value: "我的"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "店铺管理", Field: "shopsManage", Value: "店铺管理"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "商家管理", Field: "merchantManage", Value: "商家管理"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "商家入驻", Field: "merchantsSettleIn", Value: "商家入驻"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "商家服务", Field: "storeService", Value: "商家服务"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "我的订单", Field: "shopsOrder", Value: "我的订单"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "订单详情", Field: "orderDetails", Value: "订单详情"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "商品收藏", Field: "followProduct", Value: "商品收藏"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "店铺关注", Field: "followStore", Value: "店铺关注"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "浏览记录", Field: "browsingProduct", Value: "浏览记录"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "收货地址", Field: "shippingAddress", Value: "收货地址"},

		// 商品相关翻译
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "最新商品", Field: "newProduct", Value: "最新商品"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "推荐店铺", Field: "recommendedStores", Value: "推荐店铺"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "推荐分类", Field: "recommendedCategory", Value: "推荐分类"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "推荐产品", Field: "recommendedProduct", Value: "推荐产品"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "折扣商品", Field: "discountProduct", Value: "折扣商品"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "销量", Field: "sales", Value: "销量"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "商品", Field: "commodity", Value: "商品"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "评分", Field: "rating", Value: "评分"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "访问店铺", Field: "visitStore", Value: "访问店铺"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "加入购物车", Field: "addCart", Value: "加入购物车"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "联系方式", Field: "contactDetails", Value: "联系方式"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "规格", Field: "specification", Value: "规格"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "规格", Field: "specification", Value: "规格"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "待付款", Field: "pendingPayment", Value: "待付款"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "已取消", Field: "cancelled", Value: "已取消"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "已完成", Field: "completed", Value: "已完成"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "待发货", Field: "pendingShipping", Value: "待发货"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "待收货", Field: "pendingReceipt", Value: "待收货"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "待售后", Field: "pendingRefund", Value: "待售后"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "待评价", Field: "pendingReview", Value: "待评价"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "取消订单", Field: "cancelOrder", Value: "取消订单"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "删除订单", Field: "deleteOrder", Value: "删除订单"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "退货退款", Field: "returnAndRefund", Value: "退货退款"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "退款金额", Field: "refundMoney", Value: "退款金额"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "申请原因", Field: "reasonApply", Value: "申请原因"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "确认收货", Field: "confirmReceipt", Value: "确认收货"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "是否确认收货", Field: "isConfirmReceipt", Value: "是否确认收货"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "商品管理", Field: "productManage", Value: "商品管理"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "订单管理", Field: "orderManage", Value: "订单管理"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "店铺管理", Field: "storeManage", Value: "店铺管理"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "财务管理", Field: "financialManage", Value: "财务管理"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "售后管理", Field: "refundManage", Value: "售后管理"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "评价管理", Field: "commentManage", Value: "评价管理"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "批发商城", Field: "wholesaleMall", Value: "批发商城"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "上架商品", Field: "shelvesIn", Value: "上架商品"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "下架商品", Field: "shelvesOff", Value: "下架商品"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "今日", Field: "today", Value: "今日"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "昨日", Field: "yesterday", Value: "昨日"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "本月", Field: "month", Value: "本月"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "店铺Logo", Field: "storeLogo", Value: "Logo"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "店铺名称", Field: "storeName", Value: "店铺名称"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "店铺关键词", Field: "storeKeywords", Value: "关键词"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "店铺描述", Field: "storesDesc", Value: "描述"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "同意退款", Field: "agreeRefund", Value: "同意退款"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "拒绝退款", Field: "refuseRefund", Value: "拒绝退款"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "订单", Field: "order", Value: "订单"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "批发价", Field: "wholesalePrice", Value: "批发价"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "零售价", Field: "retailPrice", Value: "零售价"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "利润", Field: "profit", Value: "利润"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "商品金额", Field: "productAmount", Value: "商品金额"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "优惠金额", Field: "discountAmount", Value: "优惠金额"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "实付款", Field: "actualAmount", Value: "实付款"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "确认发货", Field: "confirmDelivery", Value: "确认发货"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "运费", Field: "shipping", Value: "运费"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "免运费", Field: "freeShipping", Value: "免运费"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "折扣", Field: "discount", Value: "折扣"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "是否确认删除", Field: "isDelete", Value: "是否确认删除"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "默认", Field: "default", Value: "默认"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "设置默认地址", Field: "setDefault", Value: "设置默认地址"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "详细地址", Field: "address", Value: "详细地址"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "店铺地址", Field: "storeAddress", Value: "店铺地址"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "营业执照", Field: "businessLicense", Value: "营业执照"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "确认付款", Field: "confirmPayment", Value: "确认付款"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "国家/城市", Field: "nationalCity", Value: "国家/城市"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "关注", Field: "follow", Value: "关注"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "已关注", Field: "followed", Value: "已关注"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "评论", Field: "comment", Value: "评价"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "已评论", Field: "commented", Value: "已评价"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "待评论", Field: "pendingComment", Value: "待收货"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "支付方式", Field: "paymentMethod", Value: "支付方式"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "订单编号", Field: "orderSn", Value: "订单编号"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "下单时间", Field: "orderTime", Value: "下单时间"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "付款时间", Field: "paymentTime", Value: "付款时间"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "常用应用", Field: "commonApplications", Value: "常用应用"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "店铺数据", Field: "storeData", Value: "店铺数据"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "订单信息", Field: "orderInfo", Value: "订单信息"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "访客", Field: "visitor", Value: "访客"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "收益", Field: "earnings", Value: "收益"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "今日订单", Field: "todayOrder", Value: "今日订单"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "今日访客", Field: "todayVisitor", Value: "今日访客"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "今日销量", Field: "todaySales", Value: "今日销量"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "用户评论", Field: "userComment", Value: "用户评论"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "商品描述", Field: "productDesc", Value: "商品描述"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "综合", Field: "comprehensive", Value: "综合"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "价格", Field: "price", Value: "价格"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "件", Field: "pieces", Value: "件"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "收藏", Field: "collect", Value: "收藏"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "店铺", Field: "store", Value: "店铺"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "客服", Field: "online", Value: "客服"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "库存", Field: "stock", Value: "库存"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "数量", Field: "nums", Value: "数量"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "商城服务", Field: "mallServices", Value: "商城服务"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "提示", Field: "tips", Value: "商城服务"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "确认取消订单", Field: "confirmCancelOrder", Value: "确认取消订单"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "拒绝理由", Field: "reasonRejection", Value: "拒绝理由"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "管理", Field: "manager", Value: "管理"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "退出管理", Field: "ExitManager", Value: "退出管理"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "总计", Field: "total", Value: "总计"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "选择", Field: "choose", Value: "选择"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "请输入", Field: "enter", Value: "请输入"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "时间", Field: "time", Value: "时间"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "立即购买", Field: "nowBuy", Value: "立即购买"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "确认订单", Field: "cmfOrder", Value: "确认订单"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "申请时间", Field: "applicationTime", Value: "申请时间"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "商品名称", Field: "productName", Value: "商品名称"},
		{Type: systemsModel.TranslateTypeFrontend, AdminId: adminsModel.SuperAdminId, Lang: "zh-CN", Name: "请选择规格", Field: "pleaseSelectTheSpecification", Value: "请选择规格"},
	}...)

	return data
}
